# dashbox app docker-compose.yml
# definis les services (module) de l'app

version: '3'

services:
  db:
    labels: "Base de donnée"
    build: .
    context: ./db
    dockerfile: Dockerfile
    expose: ["5432"]
    volumes: .:/db/data
    env_file: /db/.env




# rediriger le flux video vers sdout
# -e "DISPLAY=unix${DISPLAY}" 
